[tool.black]
line-length = 100


[tool.ruff]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
select = ["E",
          "F", "PL", # use Pyflakes and Pylint for linting
          "I", # Import sorting
          "D", # PEP257 docstring style
          "N", # PEP8 naming conventions
          "UP", # Run PyUpgrade for better practices
          "PD"]  # Pandas syntax helper
line-length = 100
ignore = ["D212"]  # Allow an empty first line when documenting functions.

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
